### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Add EOF (end of file) for every classes in `Tests` folder.
- Moving all classes to `src` folder excluding `Tests` can collect all `cache` source codes.
- Add `ext-apcu` extension requirement inside `require-dev` block to present that this have to do tests during unit tests execution.
- Travis CI build integration. The Travis CI build result is available [here](https://travis-ci.org/open-source-contributions/cache/builds/578764337).
- Since we use the `PHPUnit 8.x`, it will generate `.phpunit.result.cache` after finishing the unit test execution.
This file is a test result cache. To avoid this file under `Git` version control, add this file in `.gitignore`.

### CODE REVIEW

**Comment by beryllium** [comment]
This is awesome! Thanks so much :)

While we're shuffling files around, do you know if there's a good way for the `Tests/` folder to live as `tests/` and remove the `Tests/` namespace from the files? I haven't had a chance to experiment with it yet.

I'm a bit torn on adding the memcached and apcu extensions to the require-dev, but since travis can handle it, seems fine for now.

**Comment by peter279k** [comment]
> 
> While we're shuffling files around, do you know if there's a good way for the `Tests/` folder to live as `tests/` and remove the `Tests/` namespace from the files? I haven't had a chance to experiment with it yet.

IMHO, I think it's fine to use the `tests` folder, and I can move `Tests` to `tests` folder.

**Comment by peter279k** [comment]
@beryllium, I've moved `Tests` to `tests` folder.

If having any issue to be considered, feel free to write the comments :).

**Review by beryllium — APPROVED** [review]
This is fantastic! Thank you so much!

**Pull request merged**
